site_name: Speckit中文网

# 站点配置
site_description: Speckit项目中文文档，Spec-kit中文优化，SDD相关案例分享，Speckit中文网。
site_author: Figo
site_url: http://www.spec.xin

# 主题配置
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
  palette:
    primary: indigo
    accent: indigo
  extra_head:
    - |
      <script>
      var _hmt = _hmt || [];
      (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?0126baf0c6f09a919cd82d4cc5817409";
        var s = document.getElementsByTagName("script")[0];  
        s.parentNode.insertBefore(hm, s);
      })();
      </script>

# 插件配置
plugins:
  - search
  - mkdocstrings

# 扩展配置
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - tables

# 导航配置
nav:
  - 首页: index.md
  - 使用指南: 
    - guide/Trae.md
    - guide/VSCode.md
    - guide/CodeBuddy.md
    - guide/QCoder.md
  - SDD: 
    - SDD/SDD宣言.md
    - SDD/Openspec.md
  - 示例: 
    - examples/web应用.md
    - examples/两天完成一个数字资产交易系统.md
    - examples/iOS应用.md
    - examples/桌面应用.md
  - 第三方服务:
    - vendor/Supabase.md
    - vendor/Figma.md
  - 关于: about.md